#/usr/bin/env python

E_TYPES = {
        0:"ET_NONE  (No file type)",
        1:"ET_REL   (Relocatable file)",
        2:"ET_EXEC  (Executable file)",
        3:"ET_DYN   (Shared object file)",
        4:"ET_CORE  (Core file)",
        0xfe00:"ET_LOOS    (Operating system-specific)",
        0xfeff:"ET_HIOS    (Operating system-specific)",
        0xff00:"ET_LOPROC  (Processor-specific)",
        0xffff:"ET_HIPROC  (Processor-specific)",
        }

E_MACHINES = {
	    0 :"EM_NONE      No machine",
	    1 :"EM_M32       AT&T WE 32100",
	    2 :"EM_SPARC     SPARC",
	    3 :"EM_386       Intel 80386",
	    4 :"EM_68K       Motorola 68000",
	    5 :"EM_88K       Motorola 88000",
	    6 :"RESERVED     Reserved for future use",
	    7 :"EM_860       Intel 80860",
	    8 :"EM_MIPS      MIPS I Architecture",
	    9 :"EM_S370      IBM System/370 Processor",
	    10:"EM_MIPS_RS3_LE   MIPS RS3000 Little-endian",
	    11:"RESERVED   -14   Reserved for future use",
	    15:"EM_PARISC    Hewlett-Packard PA-RISC",
	    16:"RESERVED     Reserved for future use",
	    17:"EM_VPP500    Fujitsu VPP500",
	    18:"EM_SPARC32PLUS   Enhanced instruction set SPARC",
	    19:"EM_960       Intel 80960",
	    20:"EM_PPC       PowerPC",
	    21:"EM_PPC64     64-bit PowerPC",
	    22:"RESERVED     Reserved for future use",
	    23:"RESERVED     Reserved for future use",
	    24:"RESERVED     Reserved for future use",
	    25:"RESERVED     Reserved for future use",
	    26:"RESERVED     Reserved for future use",
	    27:"RESERVED     Reserved for future use",
	    28:"RESERVED     Reserved for future use",
	    29:"RESERVED     Reserved for future use",
	    30:"RESERVED     Reserved for future use",
	    31:"RESERVED     Reserved for future use",
	    32:"RESERVED     Reserved for future use",
	    33:"RESERVED     Reserved for future use",
	    34:"RESERVED     Reserved for future use",
	    35:"RESERVED     Reserved for future use",
	    36:"EM_V800      NEC V800",
	    37:"EM_FR20      Fujitsu FR20",
	    38:"EM_RH32      TRW RH-32",
	    39:"EM_RCE       Motorola RCE",
	    40:"EM_ARM       Advanced RISC Machines ARM",
	    41:"EM_ALPHA     Digital Alpha",
	    42:"EM_SH        Hitachi SH",
	    43:"EM_SPARCV9   SPARC Version 9",
	    44:"EM_TRICORE   Siemens Tricore embedded processor",
	    45:"EM_ARC       Argonaut RISC Core, Argonaut Technologies Inc.",
	    46:"EM_H8_300    Hitachi H8/300",
	    47:"EM_H8_300H   Hitachi H8/300H",
	    48:"EM_H8S       Hitachi H8S",
	   49:"EM_H8_500    Hitachi H8/500",
	    50:"EM_IA_64     Intel IA-64 processor architecture",
	    51:"EM_MIPS_X    Stanford MIPS-X",
	    52:"EM_COLDFIRE  Motorola ColdFire",
	    53:"EM_68HC12    Motorola M68HC12",
	    54:"EM_MMA       Fujitsu MMA Multimedia Accelerator",
	    55:"EM_PCP       Siemens PCP",
	    56:"EM_NCPU      Sony nCPU embedded RISC processor",
	    57:"EM_NDR1      Denso NDR1 microprocessor",
	    58:"EM_STARCORE  Motorola Star*Core processor",
	    59:"EM_ME16      Toyota ME16 processor",
	    60:"EM_ST100     STMicroelectronics ST100 processor",
	    61:"EM_TINYJ     Advanced Logic Corp. TinyJ embedded processor family",
        62:"EM_X86_64    Advanced Micro Devices X86-64 processor",
        63:"EM_PDSP      Sony DSP Processor ",
        64:"EM_PDP10     Digital Equipment Corp. PDP-10 ",
        65:"EM_PDP11     Digital Equipment Corp. PDP-11 ",
	    66:"EM_FX66      Siemens FX66 microcontroller",
	    67:"EM_ST9PLUS   STMicroelectronics ST9+ 8/16 bit microcontroller",
	    68:"EM_ST7       STMicroelectronics ST7 8-bit microcontroller",
	    69:"EM_68HC16    Motorola MC68HC16 Microcontroller",
	    70:"EM_68HC11    Motorola MC68HC11 Microcontroller",
	    71:"EM_68HC08    Motorola MC68HC08 Microcontroller",
	    72:"EM_68HC05    Motorola MC68HC05 Microcontroller",
	    73:"EM_SVX       Silicon Graphics SVx",
	    74:"EM_ST19      STMicroelectronics ST19 8-bit microcontroller",
	    75:"EM_VAX       Digital VAX",
	    76:"EM_CRIS      Axis Communications 32-bit embedded processor",
	    77:"EM_JAVELIN   Infineon Technologies 32-bit embedded processor",
	    78:"EM_FIREPATH  Element 14 64-bit DSP Processor",
	    79:"EM_ZSP       LSI Logic 16-bit DSP Processor",
	    80:"EM_MMIX      Donald Knuth's educational 64-bit processor",
	    81:"EM_HUANY     Harvard University machine-independent object files",
	    82:"EM_PRISM     SiTera Prism",
        83:"EM_AVR       Atmel AVR 8-bit microcontroller",
        84:"EM_FR30      Fujitsu FR30",
        85:"EM_D10V      Mitsubishi D10V",
        86:"EM_D30V      Mitsubishi D30V",
        87:"EM_V850      Renesas V850 (formerly NEC V850)",
        88:"EM_M32R      Renesas M32R (formerly Mitsubishi M32R)",
        89:"EM_MN10300   Matsushita MN10300",
        90:"EM_MN10200   Matsushita MN10200",
        91:"EM_PJ        picoJava",
        92:"EM_OR1K      OpenRISC 1000 32-bit embedded processor",
        93:"EM_ARC_A5    ARC Cores Tangent-A5",
        94:"EM_XTENSA    Tensilica Xtensa Architecture",
        95:"EM_VIDEOCORE Alphamosaic VideoCore processor",
        96:"EM_TMM_GPP   Thompson Multimedia General Purpose Processor",
        97:"EM_NS32K     National Semiconductor 32000 series",
        98:"EM_TPC       Tenor Network TPC processor",
        99:"EM_SNP1K     Trebia SNP 1000 processor",
        100:"EM_ST200     STMicroelectronics ST200 microcontroller",
        101:"EM_IP2K      Ubicom IP2022 micro controller",
        102:"EM_MAX       MAX Processor",
        103:"EM_CR        National Semiconductor CompactRISC",
        104:"EM_F2MC16    Fujitsu F2MC16",
        105:"EM_MSP430    TI msp430 micro controller",
        106:"EM_BLACKFIN  ADI Blackfin",
        107:"EM_SE_C33    S1C33 Family of Seiko Epson processors",
        108:"EM_SEP       Sharp embedded microprocessor",
        109:"EM_ARCA      Arca RISC Microprocessor",
        110:"EM_UNICORE   Microprocessor series from PKU-Unity Ltd. and MPRC of Peking University",
        111:"EM_EXCESS    eXcess: 16/32/64-bit configurable embedded CPU",
        112:"EM_DXP       Icera Semiconductor Inc. Deep Execution Processor",
        113:"EM_ALTERA_NIOAltera Nios II soft-core processor",
        114:"EM_CRX       National Semiconductor CRX",
        115:"EM_XGATE     Motorola XGATE embedded processor",
        116:"EM_C166      Infineon C16x/XC16x processor",
        117:"EM_M16C      Renesas M16C series microprocessors",
        118:"EM_DSPIC30F  Microchip Technology dsPIC30F Digital Signal Controller",
        119:"EM_CE        Freescale Communication Engine RISC core",
        120:"EM_M32C      Renesas M32C series microprocessors",
        121:"EM_res121    Reserved",
        122:"EM_res122    Reserved",
        123:"EM_res123    Reserved",
        124:"EM_res124    Reserved",
        125:"EM_res125    Reserved",
        126:"EM_res126    Reserved",
        127:"EM_res127    Reserved",
        128:"EM_res128    Reserved",
        129:"EM_res129    Reserved",
        130:"EM_res130    Reserved",
        131:"EM_TSK3000   Altium TSK3000 core",
        132:"EM_RS08      Freescale RS08 embedded processor",
        133:"EM_res133    Reserved",
        134:"EM_ECOG2     Cyan Technology eCOG2 microprocessor",
        135:"EM_SCORE     Sunplus Score",
        135:"EM_SCORE7    Sunplus S+core7 RISC processor",
        136:"EM_DSP24     New Japan Radio (NJR) 24-bit DSP Processor",
        137:"EM_VIDEOCORE3Broadcom VideoCore III processor",
        138:"EM_LATTICEMICRISC processor for Lattice FPGA architecture",
        139:"EM_SE_C17    Seiko Epson C17 family",
        140:"EM_TI_C6000  Texas Instruments TMS320C6000 DSP family",
        141:"EM_TI_C2000  Texas Instruments TMS320C2000 DSP family",
        142:"EM_TI_C5500  Texas Instruments TMS320C55x DSP family",
        143:"EM_res143    Reserved",
        144:"EM_res144    Reserved",
        145:"EM_res145    Reserved",
        146:"EM_res146    Reserved",
        147:"EM_res147    Reserved",
        148:"EM_res148    Reserved",
        149:"EM_res149    Reserved",
        150:"EM_res150    Reserved",
        151:"EM_res151    Reserved",
        152:"EM_res152    Reserved",
        153:"EM_res153    Reserved",
        154:"EM_res154    Reserved",
        155:"EM_res155    Reserved",
        156:"EM_res156    Reserved",
        157:"EM_res157    Reserved",
        158:"EM_res158    Reserved",
        159:"EM_res159    Reserved",
        160:"EM_MMDSP_PLUSSTMicroelectronics 64bit VLIW Data Signal Processor",
        161:"EM_CYPRESS_M8Cypress M8C microprocessor",
        162:"EM_R32C      Renesas R32C series microprocessors",
        163:"EM_TRIMEDIA  NXP Semiconductors TriMedia architecture family",
        164:"EM_QDSP6     QUALCOMM DSP6 Processor",
        165:"EM_8051      Intel 8051 and variants",
        166:"EM_STXP7X    STMicroelectronics STxP7x family",
        167:"EM_NDS32     Andes Technology compact code size embedded RISC processor family",
        168:"EM_ECOG1     Cyan Technology eCOG1X family",
        168:"EM_ECOG1X    Cyan Technology eCOG1X family",
        169:"EM_MAXQ30    Dallas Semiconductor MAXQ30 Core Micro-controllers",
        170:"EM_XIMO16    New Japan Radio (NJR) 16-bit DSP Processor",
        171:"EM_MANIK     M2000 Reconfigurable RISC Microprocessor",
        172:"EM_CRAYNV2   Cray Inc. NV2 vector architecture",
        173:"EM_RX        Renesas RX family",
        174:"EM_METAG     Imagination Technologies Meta processor architecture",
        175:"EM_MCST_ELBRUMCST Elbrus general purpose hardware architecture",
        176:"EM_ECOG16    Cyan Technology eCOG16 family",
        177:"EM_CR16      National Semiconductor CompactRISC 16-bit processor",
        178:"EM_ETPU      Freescale Extended Time Processing Unit",
        179:"EM_SLE9X     Infineon Technologies SLE9X core",
        180:"EM_L1OM      Intel L1OM",
        181:"EM_K1OM      Intel K1OM",
        182:"EM_INTEL182  Reserved by Intel",
        183:"EM_AARCH64   ARM 64-bit architecture",
        184:"EM_ARM184    Reserved by ARM",
        185:"EM_AVR32     Atmel Corporation 32-bit microprocessor family",
        186:"EM_STM8      STMicroeletronics STM8 8-bit microcontroller",
        187:"EM_TILE64    Tilera TILE64 multicore architecture family",
        188:"EM_TILEPRO   Tilera TILEPro multicore architecture family",
        189:"EM_MICROBLAZEXilinx MicroBlaze 32-bit RISC soft processor core",
        190:"EM_CUDA      NVIDIA CUDA architecture",
        191:"EM_TILEGX    Tilera TILE-Gx multicore architecture family",
        197:"EM_RL78      Renesas RL78 family. ",
        199:"EM_78K0R     Renesas 78K0R. ",
        205:"EM_INTEL205  Reserved by Intel",
        206:"EM_INTEL206  Reserved by Intel",
        207:"EM_INTEL207  Reserved by Intel",
        208:"EM_INTEL208  Reserved by Intel",
        209:"EM_INTEL209  Reserved by Intel",
        221:"EM_VISIUM    Controls and Data Services VISIUMcore processor",
        222:"EM_FT32      FTDI Chip FT32 high performance 32-bit RISC architecture",
        223:"EM_MOXIE     Moxie processor family",
	    }
